apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kanban-dev
  namespace: argocd
  # Allow Argo CD to clean up child resources when this Application is deleted.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # CHANGE THIS to your actual git URL.
    repoURL: https://github.com/test-application.git
    targetRevision: main
    path: .
    helm:
      releaseName: kanban-dev
      valueFiles:
        - environments/values.yml
        - environments/platform.yml
        - environments/dev.yml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true       # delete resources removed from git
      selfHeal: true    # revert manual cluster edits
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
