apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kanban-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Finboconnect/kubernetes-local.git
    targetRevision: main
    path: .
    helm:
      releaseName: kanban-prod
      valueFiles:
        - environments/values.yml
        - environments/platform.yml
        - environments/prod.yml

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
