---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-image-updater-git
  namespace: argocd
spec:
  encryptedData:
    password: AgB0DJ8RkIk9a4b86mNGkvteCcb+q2Quth3XFdgdEgyKkRKGj2BjZ6Gf9PUAGrT0zuVws/B3JiL37617YPuRmbqOadyq21vwoNBCwpPN9ze6dYBv3hZcuXnjwpI30IHKt4c7ztjnuLaAXmJDmaDNzm0OaXtTqZZd/RdGgQ9IbxRPqsYmnMBRs1UAXG5oMJ9fLz9B03FIJmZqDknxoKB7AjR8leVTy96hmpkOpDIWuCUKfD7JAG8DcxRKsklLv8EGURdEOodaDtelNghlnzQvfVMy9BzSAhd50JNvX60MnkfTVp0IUvXdJLr/mtC5a/scMeBe3E+/MYMXNHDI6Z4rWzy8E+tDl/cIBXduB2Ppvawuo3FdemKXk6Sc2lMV3zcofwA+r63dG3jbC2GHTnA/IfJDXSQz0D75+pygBu1Bnfk30CG7/Gb2Wq28vUa13wc+nnkE3vQGLgzsn4ZbaiHD/vFzzKE7nlt9jVRqwdtGyGlWzUtZNrG5wVX0IDIymcclKxQKy3LjayM/wrP/AoyvRUVziC+gy+86LEUAoOwE/tcMf3ULT7cd43sUUn32Ds9itcVUGmFVA4WKLfE7lBL6zBdEnp6vZCj2q72l2Fg22MBq5qpuulJ5LSCog3zna5Kz7vWsAI6XjVsZodrcEUyFvmOZZ6TY9jVRtVjdQy+gdAB3GCKx9zqQucXyYxYCu5yPJMXy7C9f82qLw562KTrFkU5VotMWz8nkgL9yGUU5Bj1CFj7acZuiqnIn
    username: AgCkdY2aMuEBiHm/ZH+vzl3H1S3VPxUu9nHDVcHHygYlMh9LJgt8sJyXqq90iju7vLkWLkyPracgyTiK7fakINoPd2IgNHYiADQ2jPA7LtIVeOwNezOJHM3+f0QDMnEKk4zXu+wrwwf41LXiId5cPWiyove8pbTbFl/bwU0uIN+Gwt6AcZSkzLq5tiGNTCTy57KO9mNEX4ZH2zcajMVjhDQKEkmO+6q7xC6BPaTPA3gNUwCaMeXKu/GGgCEb4CywxXxV4AfAQroDMa1D9oeoR0EAbvdWKX1A3gHZ1+U2evt91dkLkcbg/qDL2dM/sMO819BfFHiZZGwMIhXyVMTGR4qvUE4or+frTbV+O3c6fW1lZDo2QVn60K3CkiTNc3ngoSORKkUNYJZDxtspAbf0ifJzBwflgk0YNxi10vv1ZD0P/0hsx+qgLDTde5sgXXYujuV9YnajP4EM8+YWfUekyb4Fre5+kWQv/JKkJZeBZFowEqfAD83PGME7DS47wZfLtvmH6jJLhYk4th7j/0J1xva0+zfyI/gBxXj0vrXYO43NlDFMHzzhMyDRYNsweFXov0bp4hsBsD//qwo1Ie29/+PkOhDp/pqHnfAftmostHN4uvHIAZk2czfL+3VQjW00qBKVk4Mx5Dfr+Bk6MafNkLMfIJbd/pBNLUiUN8ZAFk1iXsc8i6QBRS0tPws/C/cZbE1SxsQ=
  template:
    metadata:
      name: argocd-image-updater-git
      namespace: argocd
    type: Opaque
