---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-github-token
  namespace: backstage-prod
spec:
  encryptedData:
    GITHUB_TOKEN: AgBh0zYGlBIJb5zbCWRQP+wU/SL2UYFJtBa7BiiwHpyVVZADDXEyel1ymllwqhT5sVxFQlhBgdy4Yba2zFZ1WV7cbmyiNAZ1YiwHrxW0ZJEjnwX+yaiVn9egDbrnLgG7BxnJj7o2qpHkwphRn6IbGfN0RBZ0oPpA+ayfcNP6L9uqd3ReIiq8KowXF3c7EwF2foCgb4oDml8ylgjQBJi9I0HE9KKyzuVLsOvOphI+SvkDb9VAoXyhv+HDwZ7Gai4T9pVMSGXoKueYt+6B1Z9P4fU96578DNTSdDpvd5dwV5lL7KLZS0c9TwuoHGZfs033WyqbYOew8m2f+U//AimvUihw2GBvY4ksex+XlvU1mQumR5oBsINrPN0IACTBlF8vq/aL7OoRlmsEwOqp5YEXl0u9h8NYZvAOxDj3Ng9i7qw3lwmQTA1qUPFVZya/GIkXUjmymbhjlyS1H8Ey7l65LiIZdWJmHaan6VAOAEsVsjbvHE7CKG2Z6xAKGC+d3PKJ2ycnuaCnH+8xTZv48snP10wxIA3BBUbJVcH1W2/9dz979hhtGjQCAaVJ2gv7jbRc0Te0IdUVjoxLvt5xkxGtDFl3Ltow3VQEZKXVFpyDQdf3uE8FVxtmu3NDwL/4cb/4VFDYZEfNBAPXoORb502m3fp+AVgJDr1ZUGbNM4ATv12VR3nH3TGYyMfy2890PEGKdf4SOaVKJCNtAPoQF9CL2obOT6YAYBmubp+bfrHUtYURFR+PQgfjdnDF
  template:
    metadata:
      name: backstage-github-token
      namespace: backstage-prod
