---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-postgres-creds
  namespace: backstage-prod
spec:
  encryptedData:
    password: AgAkJ4rKci5SrYnDumHlJgIqX17Y9QCbW99xvD/QN+0csLYpx9BlYEGYCdM4ur7FwhHL8C7/xyk6LR4dhXov7xp3+uA8poQNoFPbq7pObE1gWLznqpc4EzKh5EfEAqZBZFRWAFuhQR4Xu3HSVsbWg1/QWiXE1hhzkXi+zZATyGEd41YQ+QniQQAWaPrDVoT09NlEDWKhR2mKqBIbOyExKjV3EGHOcS4GvKJ7CG90okAa6NxibbdSoDE/3+VGhLVgPtLj1FWQyOIMqr8+gJp3DoM0mAAo1sLXwB0Up5YW24BkQcGvm4HWFwOZzG6T9glkQzE8xmhDnbTotshIgH/9o+8Ml1CP1ENJaVMdSHmsJA1U2k7IwaeKcUm5IfyUlyTgf5QpwXEZwU5Zb6m8SC+tIfhChIVJSee8EZJxR990rESlkKiHf7P3DZbjHp4y2cSffw1bYoGjts4BU8WVG4iGJXlQacodk4m1NWkeejori6MX3D+6S9Y/O9kPDlB44W+4sH3o07l6aa4zcmk/djC0/ZqickE7C833PtVWvrsbmGMrY00cc/sziAXBLymm7gFgsvy3UlRx+ZZC3KRZYtXhitD5KU5IrLbPVmT4A+91C5eqjSiIlFM6DRPaioIAjJUk26D8vJTR8jVhsuVfA8XnkQQyAdWiLqS+2efhOxLgXogK0ZcSfZhC4ddEQO3qrvYon2aotDj9VpZ9qKEEiCWMSlPQmcC0jk/6euo/clIVoRuNgg==
    postgres-password: AgAxthNljq9wdut9QHA5XaSGfwve3EVhafUD6foml1yXR3ijyXfX1zgCZcG8l3EHAVqz1rh6lpyyTq0JgfgTgieoizo1UpSI1uFB20GtWJMeZvonLubRSheKU/QB9fMj5F50wuOVQe4yKnlUCN3w14GnJim3ks/gSyiKhBNr6VWvtpF8oJKorC529tU+qFKfUtJmk8FUv94m2oe3fQIhSi/a5auUe8X7tM8oscXPX9VXJVHKSEj5SHk9Y6wMaq0EwRPYYVhoQ1uVTzA6xtV6iJE7qOGag194A387+NI8I9hgKCdgCoAzKuQRkQthJREt8QVurT0VyuwUg97099VMIlvVbgafvf8hn61o7scByvql0rWSaITAZzwvam1ubXR9F+fDlHZVv9F2SfgQAGQ3G67evWvmhNxkC2y3gvSpt++2vJTVfrf4Tb+sBdtjKtbmXTnuqt36vxnuLl6llQGJFYjhTlng1kWixZwLAUvwQhI9dFdS5N/j3NSd1Lk0TSD7El5ncN28kb2pEjpxOh8wxtEmpI1d/t5gmpeO4JH0ma0KbIGq9/wk1h9IA6wBH7gJyv9YOoCgYIp9reltlix9uiTa3orS6Dkoh4dfYMfpGRSIZZF9VZp6msDkOxDTunh7JKgTzuamQWLMhe3GSOJYS5VRYKeGeuuchum+L25zbOOSJvBXxS0uaTryfcBi+/mjELuVoDWK0I9cGixeyQvXN8rP0JXiXXXsa0N7j0OPzhF5gA==
  template:
    metadata:
      name: backstage-postgres-creds
      namespace: backstage-prod
