---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-github-token
  namespace: backstage-dev
spec:
  encryptedData:
    GITHUB_TOKEN: AgCxNT52MltLMujcdWVxGCjN2FwX8OTIIauKdZLQeAJ6jiatXglWk2pV7G7NnqWfZEXC8Apn3AnkstD9nShTaz3qTDGdmiGtGcuRgy3dWrqr4S/Bj+0gB9quXk0mYdeLuY9Njn4pQD19YMQ4PbGRb1NyS5CRpZNYAbZB73ZnI68RPG6EbQ+aXr0j9Jalz3W9Awp0aN4e0DEJCpim/UqXqndvKVqPPJL/ID2zSZRSfK3WfBxaHqOMB8MU+Vws3KwZbWbZHYZ7I7N/JZFpVF4i5rKOXx/GdZnFRloxhRvwY2CpNw860S/yVLgUOxDoLRhRNnf8kuxu8SRxp7v6LUH0kKQ52kbLsUIlOZWLA72fQUznj++HwZXicIuhdMZVHGXm8NmOh/9M1nE1YHbcyznzJx/0C5nHYGOMPKnZxSZUdNK7EIPiEUnyDmQwo+tPgWz/a5DvGEEAV0NQPkRUt6YEFOctLesfjDjjA5QT8duQlxksRYRTXRv5fyNEjHyGk/Zjrhu8SxcbD8Q9ckS8YoYP/MR9RTQqln4zyMSffBW7ZQ+cYEMCIpI9Slezpo77EKEm9j2S5yjqqo2XqaK3gG/GCmEe4q2PSr66k+/R5+j82u30rQGyiFwgca1TVTCsa61Wr7sqqt5Qk83bgeVZQXmS3RCYEmdu//mCFp52mYy77Vb9lyVCv96QAIUV+3pvmHjQyHjjhSxst7gvikePvtRTJlsRwQOqNCy/0ufkedKSUO7K8LGLrNdu8nUd
  template:
    metadata:
      name: backstage-github-token
      namespace: backstage-dev
