---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-postgres-creds
  namespace: backstage-dev
spec:
  encryptedData:
    password: AgAwcYvSOntYtbGLHRdQQBVCcDPkhnRrOBPHMuE9dEW3ciwjKToprvV+iJU6RFxwdGOpIetoh1JNhp4SfB3Te1c5tkn5DDcIsSBDPZQ0XhzrClBEIsJTjEt1N4d1Udh3o2Rdkf7p4I1CVAkPxyAG6rtukdEh3wKUjfYV2SxhRU9BgGUeq9ajyOudzhuSL374ceXPpXnDQQJrqfhHVeTK+qqFJSfJG8RcyYsqWIwqnO2lpSfKPLs+9RNNXHCNQqU3TUqsxbuqR0NU4Qsxk3gI4uVCT7Yt0E5GCu+0rej0zE3WYQWEtmZAqHYRmZ+Z/GLrSSD8kP/9OVqpzgrv/sMs8iqx6qxxqpZRup5Exn1idceE/jaP/x6VMcjO6uFPQKYl7g0+SEsml5JvUtyeg0HdMjmIUVxYp+3LaCOXAwq5A0/MyXN4gD4EfcrDNtjEOemgZCgV0i4rSGlLpqGAjb9zrPdjL0ZtOc0w8+TZQhnobuj5KT60NBlPoWhiF9ADsxx9sXmm3OrJ+y1k5ec2uKz2vL/iSRimbJ8cghao6voUAWJy2J7ZS/cITUsm5iMzSeLeCc9KBVOfnh4ak6+aC/2IskWG5uZm80TC1Wo+98+AvGjxNjQXFC+5X9t1WZT8NU55nyNkyifjJjDJzwWxJSHg2f0bgzV6NtSAoJ3DBFeemhEiqdsIpNl+A0LA3RbqRCbnQRPoUD0xt46gbby4vkwm9wkKH3wDDStj3Z1kwmlZrWo3uw==
    postgres-password: AgDApyRgQg1ifIPFQ7tLgjReRn9wqpgZFjY1Iphb3RDQwed3kryBiI4QiTqRTtrMY8s+05HMAps5+NVmjW9CIYNWdB6A+ofF0zoSDNvKugeu4YNzsyRbY+PBlUhkMLdmmCOBFXgG+7YNbXMWht3Kpb0J0raFM1ifjSYqFXi/DeEPtcxmsjtTZQKsfJtTdfemzfNiwwuJvERXMYLlBOW5bs/PYP/pcgKjU3EtgfrTlDrMvAIU4PZzq7p9bslY4fjtpaEW63LlFOyh7gW6Yr0SXGan2k4tlsubgW/viPRw1OGnSqqGS7dcr6GzoGO/kucVTfp4LW4fRVJGg3WSEn75LILC/blYsvgLoBG0j75mFWB03TuRgpYoSOm5bKDHlHE7McNP5TEdaHuZvIWCF2spWUItWHVQm+IJztj6OpCulOnlQL8OEutT+TzCIVIIvSu0sfymwk1xWWLNEi8L6XlX6/jNc+bsRwvsy4h5CcrL82fXkP7jTn6NjzwADVBFv1ZZDS+pCN25xKo0vGWZ5zESWty6PWjM1n/bhQCJNxNNYmPhmNmgmsBYpyzgqTXs5YxnXqWnPtdsfpC+RsFGH9SSf8UKHHtzZc4dGjyjB+86qBgcjnYp0cFDTrNBLrZUvuk7+rljxx7T6FLGCPxmaR8bdchEauTTFBoaXL9wxCveowCl71qKWubF4b7xFiKwsha2FbL84illc+NCsRgivo5UTyqZy/fnUQo4UmYpl/Nj6TkM3Q==
  template:
    metadata:
      name: backstage-postgres-creds
      namespace: backstage-dev
