---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kanban-runner-pat
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgAeJFesAjx5r90k/RGIFcyC51hB06jge78Wgs7S6fcpgwwE2W6bpDu361UwvP6nM3gDbLEGgiIDVHMI6I0Fp0eTSOH/ZF3pk5qqitCiSwZuIvlvuNs7jSFFYk/mbpFkQCtYvbwuPKLx0ZKb2wdzW/bibAUxi4g7GCV44bs64WaUUnRt2y5yPinTAnZpbrWOGVUGUiEgBwuYZgbpolTsHL0FNgfSNh8C4sIc9jONLCujk9JlDFRWzexWmumCBfrv5rioZhrHMLj0qe1K38mofmvflYBeSY0w86c7POzznfWFzQvMA1iFR9o92COHlSw3TGjor83Ac+9muP+0l2Stfl8Tqp5QSJAWVuIe+mn70hOi2cZ7ieR4Q3fUI9JHSl8nvPOQuUNH5BlLzxiXIZPrr5QbZUD3ktQCOclFjmpTcrPd+SyUWkGwoBMxyw9XLvOVhkwjpiVMl2KrRN+SzHs0uarXj7pbqAhZV/NwL1enm8Z0C2cRWBpwhg8CMVgPwQtZ4WBvTYBnDDJ9xWqnpkF5TLsaCKhPL1KtzpHNSxtEsgF4L8pfeZhdKcQXf0PG+rQW80ZIlUpyUNN3RviQSImy+aTzhQkN9CXZ2iv3P8e/E7pZoLTX7FmW7+8WYzG7a85PIkeMKvI5XVElYAh/4SkCvTYZpMDl6hyfNFTROmtbMJy5+d4P8UBZRVLrM6vlbUBO4MAbTdIHF26ZBeIGPxgbPHSajLUXBipwTC9fyyqBW7iKmcs6r2zhAwYO
  template:
    metadata:
      name: kanban-runner-pat
      namespace: arc-runners
